Update collectstatic
_always_ run collect static

diff --git a/bin/steps/collectstatic b/bin/steps/collectstatic
--- a/bin/steps/collectstatic
+++ b/bin/steps/collectstatic
@@ -15,19 +15,14 @@ set +e
 # Check if collectstatic is configured properly.
 python $MANAGE_FILE collectstatic --dry-run --noinput &> /dev/null && RUN_COLLECTSTATIC=true
 
-echo "-----> RUN_CS:" $RUN_COLLECTSTATIC
 
-# Compile assets if collectstatic appears to be kosher.
-if [ "$RUN_COLLECTSTATIC" ]; then
+echo "-----> Collecting static files"
+python $MANAGE_FILE collectstatic --noinput  2>&1 | sed '/^Copying/d;/^$/d;/^ /d' | indent
 
-    echo "-----> Collecting static files"
-    python $MANAGE_FILE collectstatic --noinput  2>&1 | sed '/^Copying/d;/^$/d;/^ /d' | indent
-
-    [ $? -ne 0 ] && {
-        echo " !     Error running manage.py collectstatic. More info:"
-        echo "       http://devcenter.heroku.com/articles/django-assets"
-    }
-fi
+[ $? -ne 0 ] && {
+    echo " !     Error running manage.py collectstatic. More info:"
+    echo "       http://devcenter.heroku.com/articles/django-assets"
+}
 
 echo
 
